apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-volume-pod
spec:
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
    - name: volume-dir
      mountPath: /data
  volumes:
  - name: volume-dir
    emptyDir: {}
