apiVersion: v1
kind: Pod
metadata:
  name: gitrepo-volume-pod
spec:
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
    - name: volume-dir
      mountPath: /data
  volumes:
  - name: volume-dir
    gitRepo:
      repository: "https://github.com/akashdktyagi/test-auto-for-people-in-hurry.git"
      revision: "main"
      directory: "."

