apiVersion: v1
kind: Pod
metadata:
  name: hostpath-volume-pod
spec:
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
    - name: volume-dir
      mountPath: /data
  volumes:
  - name: volume-dir
    hostPath:
      path: /home/akash/data
      type: DirectoryOrCreate
