apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
spec:
  containers:
    - name: mongodb
      image: mongo
      volumeMounts:
        - name: data
          mountPath: /data/db
  volumes:
    - name: data
      hostPath:
        path: /home/akash/mk8s-data/mongodb-files
        type: DirectoryOrCreate
